### ISSUE TITLE
Main Queue Setup Warning

### ISSUE THREAD

**Issue by timothystewart6** [cwhenderson20/react-native-crash-tester#1]
Thank you for this.  Noticing a warning about future version of React Native.  Posting for visibility.

```
Module CrashTester requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```

**Comment by cwhenderson20** [comment]
@timothystewart6 thanks for the report! I'll look into fixing it and releasing a new version.

**Comment by GwiYeong** [comment]
hi. same error for me.
@cwhenderson20 any update for fixing?

**Comment by cwhenderson20** [comment]
@timothystewart6 apologies for the delay here! The warning should be gone in 0.2.2.

**Comment by timothystewart6** [comment]
Thanks @cwhenderson20 !
